### ISSUE TITLE
Super Objects

### ISSUE THREAD

**Issue by Onariaginosa** [BioM404Error/BlockParty#13]
Create set of objects that is to be queried

**Comment by Onariaginosa** [comment]
Diagrams of an object in the massive set of objects.
    Every object has the key:
- name (string)
- type (string type: 'entertainment')
- subType (null or subtype string: 'solo artist')
- city( string city name)
- capacity (number)
- availableTimes (object with day as key, timeRange string as value: {weekday: [timeRange1, timeRange2, ...]
- booked (set of length 2 string arrays: [day, time] )
- price (number)

![thumbnail_IMG_20201101_231941532](https://user-images.githubusercontent.com/21343072/97842286-3e433580-1c9c-11eb-8f00-ba4c2bcb2b37.jpg)
![thumbnail_IMG_20201101_232527335](https://user-images.githubusercontent.com/21343072/97842444-764a7880-1c9c-11eb-8794-209a7840c12c.jpg)

**Comment by boconno808** [comment]
Business: 
	Name:
	Type:
	Subtype:
	Location:
	startTime:
	endTime:
	Photo:
	Description:
	Price:

Location: 
	Name: 
	Capacity: 
	Photo:
	startTime:
	endTime:
	price:
	City:

**Comment by boconno808** [comment]
actually they should have unique ids too :)
Business: 
	id:
	Name:
	Type:
	Subtype:
	Location:
	startTime:
	endTime:
	Photo:
	Description:
	Price:

Location: 
	id:
	Name: 
	Capacity: 
	Photo:
	startTime:
	endTime:
	price:
	City:

**Comment by boconno808** [comment]
**Business:** 
```
	id:string
	name:string
	type:string
	subtype:string
	location:string
	startTime:[int,int]
	endTime:[int,int]
	Photo:string
	description:string
	Price:int
	daysOpen:{
		Sun:bool, 
		Mon:bool, 
		Tues:bool, 
		Wed:bool, 
		Thur:bool, 
		Fri:bool,
		Sat:bool
	} 
```
```
{
    id: "1b",
    name: "Zippys",
    type: "Food",
    subtype: "Restaurant",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "",
    description: "#1 Chili",
    price: 5.0,
    daysOpen: {
      Sun: true,
      Mon: false,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
```

**Location:** 
```
	id:string
	name: string
	capacity:int
	photo:string
	startTime:[int, int]
	endTime:[int, int]
	price:int
	city:string
	daysOpen:{
		Sun:bool, 
		Mon:bool, 
		Tues:bool, 
		Wed:bool, 
		Thur:bool, 
		Fri:bool,
		Sat:bool
	} 
```
```
	id:"23b"
	name: "Middlebury Park"
	capacity:1000
	photo:"./images/etc"
	startTime:[7, 0]
	endTime:[20, 0]
	price:150
	city:"Sacramento"
	daysOpen:{
		Sun:false, 
		Mon:true, 
		Tues:true, 
		Wed:true, 
		Thur:true, 
		Fri:true,
		Sat:false
	} 
```
